"""Add video and payment models

Revision ID: e060a2cf5571
Revises: 09b7222b71aa
Create Date: 2025-05-27 07:28:49.300855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e060a2cf5571'
down_revision = '09b7222b71aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
